### PR TITLE
Add a Dockerfile for future Docker support Updated (fix fortunes.txt)

### PR DESCRIPTION
**Pull request by upchui**
I forgot the docker fortunes.txt, here it is now. It would be great if you could include this in your repository, so I don't need to create my own and maintain it to build a container image. Whenever you make a change in the repo, I will automatically build a new image using a Jenkins pipeline.

Greetings from Austria.

### CODE REVIEW

**Review by TheCommsChannel — APPROVED** [review]

**Comment by TheCommsChannel** [comment]
Sure thing! It's been added.

**Comment by upchui** [comment]
Thank you :)

I will start building the pipeline right away. Then I'll send you the link to the Docker Hub page. I will write the documentation for the Docker container image as soon as I have completed that.

**Comment by TheCommsChannel** [comment]
Sure thing!

Thank you for putting it together! I'll have to learn more about docker :-)

**Comment by upchui** [comment]
Hello, here is the link: https://hub.docker.com/r/thealhu/tc2-bbs-mesh
I will write the documentation shortly, and it will also be visible on the page.

If you like, you can mention this in the readme.md file so it can be easily found.

Every time you update the code on GitHub, a new Docker image will be automatically built.

The image supports amd64 and arm64, so it works with anything from the Pi 3 onwards that has a 64-bit CPU.

**Comment by upchui** [comment]
The documentation is now also done, I hope it is fine this way.  :)

**Pull request merged**
