### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by jflaflamme**
- Added DB_FILE and CONFIG_FILE ENV vars support
- Added Docker support  
`docker build -t <tag> .`
- Launching a docker container with persistent data
`docker run -it --name tc2bbsmesh -v tc2bbsmesh-config:/app/config/ -v tc2bbsmesh-data:/app/data/  --device=/dev/ttyACM0 tc2-bbs-mesh`
- Support for persistent data and config under Docker (the config.ini.sample will be copied to config.ini automatically)
- Updated README for the above

### CODE REVIEW

**Comment by typicalaimster** [comment]
I did something similar, but went one step further with a docker-compose file. That way you can just do a docker-compose up (-d). Especially if you're using TCP. Something similar to this..

`
version: '3.8'

services:
  tc2-bbs-mesh:
    container_name: tc2-bbs-mesh
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.ini:/TC2-BBS-mesh/config.ini
      - ./bulletins.db:/TC2-BBS-mesh/bulletins.db
      - ./fortunes.txt:/TC2-BBS-mesh/fortunes.txt
    command: python server.py

`

**Comment by typicalaimster** [comment]
Def. I'd say have @TheCommsChannel merge your changes in and I can add my docker-compose after.

**Comment by TheCommsChannel** [comment]
New to docker but I'll merge as soon as I can test.

**Comment by g7ufo** [comment]
Came to this repo to add a docker build but have been beaten to it 😄. Nice work.

Once this is merged I can chip in with a GitHub Action to build an image automatically when a new release has been published (or new changes merged) by @TheCommsChannel

**Comment by TheCommsChannel** [comment]
I'm open to it. I'm just not familiar enough with docker yet.

**Comment by TheCommsChannel** [comment]
@jflaflamme @typicalaimster Reach out on Discord if you can

**Comment by TheCommsChannel** [comment]
> > @jflaflamme @typicalaimster Reach out on Discord if you can
> 
> I would love to but I do not have the invite to the discord server. How to find you?
> Cannot find with @The_Comms_Channel or thecommaschannel on discord.
> 

My bad. Here is the link to it https://discord.gg/XGhftQw9Mt

**Pull request closed without merging**
